/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Reinaldo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        itmIDDuncionario = new javax.swing.JMenu();
        itmCadastrar = new javax.swing.JMenuItem();
        itmListar = new javax.swing.JMenuItem();
        itmConsultar = new javax.swing.JMenuItem();
        itmListarFuncionario = new javax.swing.JMenuItem();
        itmExcluir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmCadastrarDepartamento = new javax.swing.JMenuItem();
        itmAlterarDepartamento = new javax.swing.JMenuItem();
        itmConsultarDepartamento = new javax.swing.JMenuItem();
        itmExcluirDepartamento = new javax.swing.JMenuItem();
        itmListarDepartamento = new javax.swing.JMenuItem();
        itmNomeCliente = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        itmCPFCliente = new javax.swing.JMenuItem();
        itmTelefoneCliente = new javax.swing.JMenuItem();
        itmEnderecoCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itmCodigo = new javax.swing.JMenuItem();
        itmDebito = new javax.swing.JMenuItem();
        itmCredito = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itmPlacaCarro = new javax.swing.JMenuItem();
        itmMarcaCarro = new javax.swing.JMenuItem();
        itmModelo = new javax.swing.JMenuItem();
        itmAnoFabricacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");

        itmIDDuncionario.setText("Funcionario");

        itmCadastrar.setText("Cadastrar");
        itmCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarActionPerformed(evt);
            }
        });
        itmIDDuncionario.add(itmCadastrar);

        itmListar.setText("Listar");
        itmIDDuncionario.add(itmListar);

        itmConsultar.setText("Consultar");
        itmIDDuncionario.add(itmConsultar);

        itmListarFuncionario.setText("Listar");
        itmIDDuncionario.add(itmListarFuncionario);

        itmExcluir.setText("Excluir");
        itmIDDuncionario.add(itmExcluir);

        jMenuBar1.add(itmIDDuncionario);

        jMenu2.setText("Departamento");

        itmCadastrarDepartamento.setText("Cadastrar");
        jMenu2.add(itmCadastrarDepartamento);

        itmAlterarDepartamento.setText("Alterar");
        jMenu2.add(itmAlterarDepartamento);

        itmConsultarDepartamento.setText("Consultar");
        jMenu2.add(itmConsultarDepartamento);

        itmExcluirDepartamento.setText("Excluir");
        jMenu2.add(itmExcluirDepartamento);

        itmListarDepartamento.setText("Listar");
        jMenu2.add(itmListarDepartamento);

        jMenuBar1.add(jMenu2);

        itmNomeCliente.setText("Cliente");

        jMenuItem9.setText("Nome");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        itmNomeCliente.add(jMenuItem9);

        itmCPFCliente.setText("CPF");
        itmNomeCliente.add(itmCPFCliente);

        itmTelefoneCliente.setText("Telefone");
        itmNomeCliente.add(itmTelefoneCliente);

        itmEnderecoCliente.setText("Endereço");
        itmNomeCliente.add(itmEnderecoCliente);

        jMenuBar1.add(itmNomeCliente);

        jMenu4.setText("Pagamento");

        itmCodigo.setText("Código CVV");
        jMenu4.add(itmCodigo);

        itmDebito.setText("Debito");
        jMenu4.add(itmDebito);

        itmCredito.setText("Crédito");
        jMenu4.add(itmCredito);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Carros");

        itmPlacaCarro.setText("Placa");
        itmPlacaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPlacaCarroActionPerformed(evt);
            }
        });
        jMenu5.add(itmPlacaCarro);

        itmMarcaCarro.setText("Marca");
        jMenu5.add(itmMarcaCarro);

        itmModelo.setText("Modelo do Carro");
        jMenu5.add(itmModelo);

        itmAnoFabricacao.setText("Ano de Fabricação");
        jMenu5.add(itmAnoFabricacao);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(447, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarActionPerformed
        new CadastrarUsuario().setVisible(true);
    }//GEN-LAST:event_itmCadastrarActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        new Cliente().setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void itmPlacaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPlacaCarroActionPerformed
        new CadastrarCarro().setVisible(true);
    }//GEN-LAST:event_itmPlacaCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarDepartamento;
    private javax.swing.JMenuItem itmAnoFabricacao;
    private javax.swing.JMenuItem itmCPFCliente;
    private javax.swing.JMenuItem itmCadastrar;
    private javax.swing.JMenuItem itmCadastrarDepartamento;
    private javax.swing.JMenuItem itmCodigo;
    private javax.swing.JMenuItem itmConsultar;
    private javax.swing.JMenuItem itmConsultarDepartamento;
    private javax.swing.JMenuItem itmCredito;
    private javax.swing.JMenuItem itmDebito;
    private javax.swing.JMenuItem itmEnderecoCliente;
    private javax.swing.JMenuItem itmExcluir;
    private javax.swing.JMenuItem itmExcluirDepartamento;
    private javax.swing.JMenu itmIDDuncionario;
    private javax.swing.JMenuItem itmListar;
    private javax.swing.JMenuItem itmListarDepartamento;
    private javax.swing.JMenuItem itmListarFuncionario;
    private javax.swing.JMenuItem itmMarcaCarro;
    private javax.swing.JMenuItem itmModelo;
    private javax.swing.JMenu itmNomeCliente;
    private javax.swing.JMenuItem itmPlacaCarro;
    private javax.swing.JMenuItem itmTelefoneCliente;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
